ContactBook/Controllers/ContactBookController.cs
using ContactBook.Models;
using ContactBook.Services.InterFace;
using ContactBook.ViewModel;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace ContactBook.Controllers
{
    public class ContactBookController : Controller
    {
        private readonly IContactService contactService;
        public ContactBookController(IContactService iContactService)
        {
            contactService = iContactService;
        }

        public ActionResult Index()
        {
            try
            {
                List<ContactViewModel> contactList = contactService.GetContacts();
                List<ContactViewModel> contactViewModel = new List<ContactViewModel>();

                if (contactList != null)
                {
                    foreach (ContactViewModel contact in contactList)
                    {
                        contactViewModel.Add(contact);
                    }
                }

                ViewBag.contactViewModel = contactViewModel;
                return View(contactViewModel);
            }
            catch (Exception exe)
            {
                return View("Error");
            }
        }

        public ActionResult AddContact()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddContactSubmit(Contact con)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    contactService.AddContact(con);

                    return RedirectToAction("Index");
                }
                else
                {
                    return View(con);
                }
            }
            catch (Exception exe)
            {
                return View("Error");
            }
        }

        public ActionResult EditContact(int id)
        {
            try
            {
                ContactViewModel contactViewModel = new ContactViewModel();
                Contact contact = new Models.Contact();
                contactViewModel = contactService.GetContactById(id);

                if (contactViewModel != null)
                {
                    contact.ContactId = contactViewModel.ContactId;
                    contact.FirstName = contactViewModel.FirstName;
                    contact.LastName = contactViewModel.LastName;
                    contact.PhoneNumber = contactViewModel.PhoneNumber;
                    contact.EmailID = contactViewModel.EmailId;
                    contact.IsActive = contactViewModel.IsActive;
                }

                return View(contact);
            }
            catch (Exception exe)
            {
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult EditContactSubit(Contact contact)
        {
            try
            {
                contactService.UpdateContact(contact);
                return RedirectToAction("Index");
            }
            catch (Exception exe)
            {
                return View("Error");
            }
        }
        public ActionResult DeleteContact(int id)
        {
            try
            {
                contactService.DeleteContact(id);
                return RedirectToAction("Index");
            }
            catch (Exception exe)
            {
                return View("Error");
            }
        }

        public bool ActiveInactive(int id)
        {
            try
            {
                ContactViewModel contactViewModel = contactService.GetContactById(id);

                if (contactViewModel.IsActive)
                {
                    contactService.InActivateContact(id);
                    contactViewModel.IsActive = false;
                }
                else
                {
                    contactService.ActivateContact(id);
                    contactViewModel.IsActive = true;
                }
                return contactViewModel.IsActive;
            }
            catch (Exception exe)
            {
                return false;
            }
        }
    }
}

ContactBook/Views/ContactBook/AddContact.cshtml
@model ContactBook.Models.Contact
@{
    ViewBag.Title = "AddContact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AddContact</h2>

@using (Html.BeginForm("AddContactSubmit", "ContactBook", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    @Html.AntiForgeryToken()     //we need this for prevent CSRF Attack    

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control", placeholder = "Enter first name" })
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>
    </div>

    //Same Way We will do all
    <div class="form-group">
        @Html.LabelFor(model => model.LastName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.LastName, new { @class = "form-control", placeholder = "Enter last name" })
            @Html.ValidationMessageFor(model => model.LastName)
        </div>
    </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control", placeholder = "Enter PhoneNumber" })
                @Html.ValidationMessageFor(model => model.PhoneNumber)
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.EmailID, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.EmailID, new { @class = "form-control", placeholder = "Enter Email ID" })
                @Html.ValidationMessageFor(model => model.EmailID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")

ContactBook/Views/ContactBook/EditContact.cshtml
@model ContactBook.Models.Contact
@{
    ViewBag.Title = "UpdateContact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>UpdateContact</h2>

@using (Html.BeginForm("EditContactSubit", "ContactBook", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    @Html.AntiForgeryToken()     //we need this for prevent CSRF Attack

    @Html.HiddenFor(model => model.ContactId)

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control", placeholder = "Enter first name" })
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.LastName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.LastName, new { @class = "form-control", placeholder = "Enter last name" })
            @Html.ValidationMessageFor(model => model.LastName)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.PhoneNumber, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control", placeholder = "Enter PhoneNumber" })
            @Html.ValidationMessageFor(model => model.PhoneNumber)
        </div>
    </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailID, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.EmailID, new { @class = "form-control", placeholder = "Enter Email ID" })
                @Html.ValidationMessageFor(model => model.EmailID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")

ContactBook/Views/ContactBook/Index.cshtml
@model IEnumerable<ContactBook.ViewModel.ContactViewModel>
@{
    ViewBag.Title = "Contact List";
    var grid = new WebGrid(source: Model, canPage: false);
}
<h3>Contact List</h3>
<div style="overflow:auto">

    @grid.GetHtml(
        htmlAttributes: new { id = "contactGrid" },
        tableStyle: "table table-responsive",

        columns: grid.Columns
            (
                grid.Column("ContactId", "ContactID"),
                grid.Column("FirstName", "First Name"),
                grid.Column("LastName", "Last Name"),
                grid.Column("PhoneNumber", "Phone Number"),
                grid.Column("EmailID", "Email ID"),
                grid.Column("Edit", format: (item) => Html.ActionLink("Edit", "EditContact", "ContactBook", new { id = item.ContactID }, null)),
                grid.Column("Delete", format: (item) => Html.ActionLink("Delete", "DeleteContact", "ContactBook", new { id = item.ContactID }, null)),
                grid.Column("Active/InActive", format: (item) => Html.ActionLink("Active/InActive", "ActiveInactive", "ContactBook", new { id = item.ContactID }, new { @class = "select" }))
            )
        )
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>

    <script type="text/javascript">

        var count=@Model.Count();
        var contacts = @Html.Raw(Json.Encode(@ViewBag.contactViewModel));
        var row = $("#contactGrid").find("tr");

        for (var i = 0; i < count; i++) {
            if(!contacts[i].IsActive)
            {
                row.eq(i+1).find("td").eq(0).css("color", "red");
                row.eq(i+1).find("td").eq(1).css("color", "red");
                row.eq(i+1).find("td").eq(2).css("color", "red");
                row.eq(i+1).find("td").eq(3).css("color", "red");
                row.eq(i+1).find("td").eq(4).css("color", "red");
                row.eq(i+1).find("td a:contains('Edit')").css("display", "none");
                row.eq(i+1).find("td a:contains('Delete')").css("display", "none");
            }
        }
        $("#contactGrid").on("click",".select", function () {
            var row = $(this).closest("tr");
            var id = row.find("td").eq(0).text();
            $.ajax({
                Type:"GET",
                ContentType: "application/json;charset=utf-8",
                cache:false,
                url:'@Url.Action("ActiveInactive", "ContactBook")',
                data:{id:id},
                success: function (isActive) {
                    checkActiveInactive(isActive);
                },
            });
            function checkActiveInactive(isActive)
            {
                if (isActive=="False")
                {
                    row.find("td").eq(0).css("color", "red");
                    row.find("td").eq(1).css("color", "red");
                    row.find("td").eq(2).css("color", "red");
                    row.find("td").eq(3).css("color", "red");
                    row.find("td").eq(4).css("color", "red");
                    row.find("td a:contains('Edit')").css("display", "none");
                    row.find("td a:contains('Delete')").css("display", "none");
                }
                else {
                    row.find("td").eq(0).css("color", "black");
                    row.find("td").eq(1).css("color", "black");
                    row.find("td").eq(2).css("color", "black");
                    row.find("td").eq(3).css("color", "black");
                    row.find("td").eq(4).css("color", "black");
                    row.find("td a:contains('Edit')").css("display", "inline");
                    row.find("td a:contains('Delete')").css("display", "inline");
                }
            }
            return false;
        });
    </script>

</div>